---

- name: Create users
  ansible.builtin.user:
    name: "{{ user.username }}"
    createhome: "{{ user.createhome | default(createhome) }}"
    group: "{{ user.group | default(omit) }}"
    groups: "{{ user.groups | join(',') if user.groups is defined else omit }}"
    password: "{{ user.password | default(omit) | password_hash('sha512', user.password_salt) }}"
    shell: "{{ user.shell | default(shell) }}"
  loop: "{{ user_list }}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"